micronaut:
  application:
    name: complete
---
#tag::security[]
micronaut:
  security:
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator: # <2>
              secret: pleaseChangeThisSecretForANewOne  # <3>
#end::security[]
#tag::ldap[]
    ldap:
      default: # <1>
        context:
          server: 'ldap://ldap.forumsys.com:389'  # <2>
          managerDn: 'cn=read-only-admin,dc=example,dc=com'  # <3>
          managerPassword: 'password'  # <4>
        search:
          base: "dc=example,dc=com"  # <5>
        groups:
          enabled: true  # <6>
          base: "dc=example,dc=com" # <7>

#end::ldap[]
---
#tag::datasource[]
hibernate:
  hbm2ddl:
    auto: update
dataSource:
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#end::datasource[]